import { Card } from "@/components/ui/Card";
import { PageHeader } from "@/components/ui/PageHeader";

const steps = [
  {
    num: "01",
    icon: "badge",
    title: "Your Context",
    desc: "You provide your current situation — school day, at home, on a budget — along with what foods are available to you and any dietary preferences.",
    detail: "Context parameters include: situation type, available foods, budget range, dietary restrictions.",
  },
  {
    num: "02",
    icon: "record_voice_over",
    title: "Your Question",
    desc: "You submit a plain-language question about nutrition — anything from \"what should I eat for lunch?\" to \"what is the glycemic index?\"",
    detail: "Questions are processed in natural language without requiring special formatting or keywords.",
  },
  {
    num: "03",
    icon: "dataset",
    title: "Knowledge Retrieval",
    desc: "SMANU searches the structured nutrition knowledge base using vector semantic retrieval via Astra DB, finding the most relevant chunks of information.",
    detail: "Retrieval is powered by Astra DB vector embeddings and routed through an IBM Langflow pipeline.",
  },
  {
    num: "04",
    icon: "psychology",
    title: "Context-Aware Reasoning",
    desc: "The AI model receives both your context and the retrieved knowledge chunks. It generates an answer grounded strictly in the retrieved evidence.",
    detail: "Responses are generated by OpenAI GPT-4o-mini, constrained to only use retrieved knowledge — no hallucination.",
  },
  {
    num: "05",
    icon: "assignment_turned_in",
    title: "Structured Answer",
    desc: "You receive a clear, structured response with sections for the main answer, reasoning, practical suggestions, and source citations.",
    detail: "Every answer includes source citations linking back to the knowledge base entries used.",
  },
];

export default function HowItWorksPage() {
  return (
    <div className="max-w-2xl mx-auto flex flex-col gap-6">
      <PageHeader
        badge="Architecture"
        title="How It Works"
        subtitle="A transparent look at SMANU's retrieval-based AI workflow."
      />

      {/* Architecture overview */}
      <Card variant="low" className="flex items-center gap-3">
        <span className="material-symbols-outlined text-[--color-secondary] text-[20px]">account_tree</span>
        <p className="text-xs text-[--color-on-surface-variant]">
          SMANU uses a <strong className="text-[--color-on-surface]">Retrieval-Augmented Generation (RAG)</strong>{" "}
          architecture — meaning answers come from a curated knowledge base, not from general AI
          knowledge. This ensures responses are accurate, grounded, and educational.
        </p>
      </Card>

      {/* Step by step */}
      <div className="flex flex-col gap-4">
        {steps.map((step, i) => (
          <div key={step.num} className="flex gap-4">
            {/* Number + line */}
            <div className="flex flex-col items-center flex-shrink-0">
              <div className="w-10 h-10 rounded-xl bg-[--color-primary-container] flex items-center justify-center text-[--color-on-primary] font-bold text-sm">
                {step.num}
              </div>
              {i < steps.length - 1 && (
                <div className="w-px flex-1 bg-[--color-outline-variant] mt-2 min-h-[2rem]" />
              )}
            </div>

            {/* Content */}
            <Card className="flex-1 mb-4">
              <div className="flex items-center gap-2 mb-2">
                <span className="material-symbols-outlined text-[--color-secondary] text-[20px]">
                  {step.icon}
                </span>
                <h3 className="text-base font-semibold text-[--color-on-surface]">{step.title}</h3>
              </div>
              <p className="text-sm text-[--color-on-surface-variant] leading-relaxed mb-3">
                {step.desc}
              </p>
              <div className="flex items-start gap-2 p-3 bg-[--color-surface-container-low] rounded-lg">
                <span className="material-symbols-outlined text-[--color-secondary] text-[14px] mt-0.5 flex-shrink-0">
                  info
                </span>
                <p className="text-[11px] text-[--color-on-surface-variant]">{step.detail}</p>
              </div>
            </Card>
          </div>
        ))}
      </div>

      {/* Flow diagram */}
      <Card>
        <h2 className="text-sm font-semibold text-[--color-on-surface] mb-4">
          Pipeline Overview
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-2">
          {[
            { n: "1", label: "Your Question" },
            { n: "2", label: "Knowledge Retrieval" },
            { n: "3", label: "Relevant Context" },
            { n: "4", label: "AI Response", highlight: true },
          ].map((item) => (
            <div
              key={item.n}
              className={`p-3 rounded-lg flex sm:flex-col items-center sm:items-start gap-2 ${
                item.highlight
                  ? "bg-[--color-secondary-container]/20"
                  : "bg-[--color-surface-container-low]"
              }`}
            >
              <span
                className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 ${
                  item.highlight
                    ? "bg-[--color-secondary] text-[--color-on-secondary]"
                    : "bg-[--color-surface-container] text-[--color-on-surface]"
                }`}
              >
                {item.n}
              </span>
              <span
                className={`text-sm ${
                  item.highlight
                    ? "text-[--color-on-surface] font-semibold"
                    : "text-[--color-on-surface-variant]"
                }`}
              >
                {item.label}
              </span>
            </div>
          ))}
        </div>
      </Card>

      {/* Note */}
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-4">
        <p className="text-xs text-amber-700 leading-relaxed">
          <strong>Phase 2 Note:</strong> Astra DB vector retrieval and IBM Langflow pipeline
          integration are planned for the next development phase. The UI currently demonstrates
          the full workflow structure.
        </p>
      </div>
    </div>
  );
}
